# Generated by Django 6.0.2 on 2026-05-08 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('stress', '😫 Stress'), ('calm', '😌 Calm'), ('angry', '😡 Angry'), ('excited', '🤩 Excited')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='date',
        ),
    ]
