# Generated by Django 6.0.2 on 2026-06-04 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unique_email_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reading_time', models.IntegerField(default=0)),
                ('total_listening_time', models.IntegerField(default=0)),
                ('pages_completed', models.IntegerField(default=0)),
                ('books_completed', models.IntegerField(default=0)),
                ('reading_streak', models.IntegerField(default=0)),
                ('last_reading_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_key', models.CharField(max_length=50)),
                ('current_page', models.IntegerField(default=0)),
                ('current_sentence', models.IntegerField(default=0)),
                ('percentage_completed', models.FloatField(default=0.0)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book_key')},
            },
        ),
    ]
