from django.contrib import admin
from django.urls import path
from . import views
from journal.views import journal_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name="index"),
    path('login/', views.auth_page, name="login"),
    path('signup/', views.auth_page, name="signup"),
    path('verify-otp/', views.verify_otp, name="verify_otp"),
    path('resend-otp/', views.resend_otp, name="resend_otp"),
    path('otp-success/', views.otp_success, name="otp_success"),
    path('mood/', views.mood_tracker, name="mood"),
    path('save-mood/', views.save_mood, name="save_mood"),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('mood-quiz/', views.mood_quiz, name='mood_quiz'),
    path('monthly-report/', views.monthly_report, name='monthly_report'),
    path('logout/', views.logout_view, name="logout"),
    path('journal/', journal_view, name='journal'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('chatbot/clear/', views.clear_chatbot_view, name='clear_chatbot'),
    path('chatbot/delete/', views.delete_chat_view, name='delete_chat'),
    path('mood-graph/', views.mood_graph, name='mood_graph'),
    path('add-mood/', views.add_mood, name='add_mood'),
    path('selfhelp/', views.self_help, name='selfhelp'),
    path('sound/', views.sound, name='sound'),
    path('reading/', views.reading, name='reading'),
    path('games/', views.games, name='games'),
    path('breathing/', views.breathing, name='breathing'),
    path('book/atomic/', views.book_atomic, name='book_atomic'),
    path('book/power-now/', views.book_power_now, name='book_power_now'),
    path('book/you-can-win/', views.book_you_can_win, name='book_you_can_win'),
    path('book/heal-life/', views.book_heal_life, name='book_heal_life'),
    path('book/overthinking/', views.book_overthinking, name='book_overthinking'),
    path('book/mindfulness/', views.book_mindfulness, name='book_mindfulness'),
    path('games/chess/', views.chess_game, name='chess_game'),
    path('games/sudoku/', views.sudoku_game, name='sudoku_game'),
    path('games/bubble/', views.bubble_game, name='bubble_game'),
    path('games/color/', views.color_game, name='color_game'),
    path('games/memory/', views.memory_game, name='memory_game'),
    path('games/number/', views.number_game, name='number_game'),
    path('admin-users/', views.admin_users, name='admin_users'),
    path("meditation/", views.meditation, name="meditation"),
    path("meditation/breathe/", views.breathe, name="breathe"),
    path("meditation/om/", views.om, name="om"),
    path("meditation/bodyscan/", views.bodyscan, name="bodyscan"),
    path("meditation/gratitude/", views.gratitude, name="gratitude"),
    path('reading/progress/', views.reading_progress, name='reading_progress'),
    path('reading/track-time/', views.reading_track_time, name='reading_track_time'),
    path('reading/ai/', views.reading_ai, name='reading_ai'),
]